# Введение в искусственные нейронные сети
# Урок 5. Рекуррентные нейронные сети|

1. Попробуйте изменить параметры нейронной сети, работающей с датасетом imdb, либо нейронной сети, работающей airline-passengers (она прилагается вместе  с датасетом к уроку в виде отдельного скрипта) так, чтобы улучшить её точность. Приложите анализ

2. Попробуйте изменить параметры нейронной сети, генерирующей текст таким образом, чтобы добиться генерации как можно более осмысленного текста. Пришлите лучший текст из получившихся и опишите предпринятые для его получения действия. Можно использовать текст другого произведения


In [3]:
from __future__ import print_function

import numpy as np

from keras.layers import Dense, Activation
from keras.layers.recurrent import SimpleRNN, LSTM, GRU
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.datasets import imdb

In [4]:
def compare(max_features, maxlen, batch_size):
  (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

  x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
  x_test = sequence.pad_sequences(x_test, maxlen=maxlen)

  model = Sequential()
  model.add(Embedding(max_features, 128))
  model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(loss='binary_crossentropy',
              optimizer='adamax',
              metrics=['accuracy'])
  
  model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=1, 
          validation_data=(x_test, y_test))
  
  score, acc = model.evaluate(x_test, y_test,
                            batch_size=batch_size)
  
  print('Результат при тестировании:', score)
  print('Тестовая точность:', acc)

**Зафиксируем параметры maxlen = 125 и batch_size = 200, изменяя параметр max_features = [15000, 17500, 20000, 21000].**

In [5]:
for m in [15000, 17500, 20000, 21000]:
  print(f'\nПри max_features = {m}:\n')
  compare(m, 125, 200)


При max_features = 15000:

125/125 [==============================] - 7s 56ms/step - loss: 0.3613 - accuracy: 0.8391
Результат при тестировании: 0.36133596301078796
Тестовая точность: 0.8391199707984924

При max_features = 17500:

125/125 [==============================] - 7s 56ms/step - loss: 0.3799 - accuracy: 0.8362
Результат при тестировании: 0.3799389600753784
Тестовая точность: 0.8362399935722351

При max_features = 20000:

125/125 [==============================] - 7s 57ms/step - loss: 0.3748 - accuracy: 0.8370
Результат при тестировании: 0.3748139441013336
Тестовая точность: 0.8370400071144104

При max_features = 21000:

125/125 [==============================] - 7s 55ms/step - loss: 0.3838 - accuracy: 0.8384
Результат при тестировании: 0.3838413953781128
Тестовая точность: 0.8384400010108948


**Зафиксируем параметры max_features = 20000 и batch_size = 200, изменяя параметр maxlen = [100, 110, 125, 150].**

In [6]:
for n in  [100, 110, 125, 150]:
  print(f'\nПри maxlen = {n}:\n')
  compare(20000, n, 200)


При maxlen = 100:

125/125 [==============================] - 5s 44ms/step - loss: 0.4047 - accuracy: 0.8145
Результат при тестировании: 0.40465807914733887
Тестовая точность: 0.814520001411438

При maxlen = 110:

125/125 [==============================] - 6s 47ms/step - loss: 0.3821 - accuracy: 0.8279
Результат при тестировании: 0.3820858597755432
Тестовая точность: 0.8279200196266174

При maxlen = 125:

125/125 [==============================] - 7s 55ms/step - loss: 0.4106 - accuracy: 0.8097
Результат при тестировании: 0.4106273949146271
Тестовая точность: 0.809719979763031

При maxlen = 150:

125/125 [==============================] - 8s 65ms/step - loss: 0.3773 - accuracy: 0.8406
Результат при тестировании: 0.3773038685321808
Тестовая точность: 0.8406000137329102


**Зафиксируем параметры max_features = 20000 и maxlen = 125, изменяя параметр batch_size = [150, 175, 200, 250].**

In [7]:
for q in [150, 175, 200, 250]:
  print(f'\nПри batch_size = {q}:', '\n', )
  compare(20000, 125, q)


При batch_size = 150: 

167/167 [==============================] - 9s 54ms/step - loss: 0.3817 - accuracy: 0.8375
Результат при тестировании: 0.3817164897918701
Тестовая точность: 0.8375200033187866

При batch_size = 175: 

143/143 [==============================] - 8s 55ms/step - loss: 0.3627 - accuracy: 0.8400
Результат при тестировании: 0.3626728951931
Тестовая точность: 0.839959979057312

При batch_size = 200: 

125/125 [==============================] - 7s 56ms/step - loss: 0.3979 - accuracy: 0.8374
Результат при тестировании: 0.39792972803115845
Тестовая точность: 0.837440013885498

При batch_size = 250: 

100/100 [==============================] - 6s 55ms/step - loss: 0.3888 - accuracy: 0.8244
Результат при тестировании: 0.3887760639190674
Тестовая точность: 0.8244400024414062


Рост значения параметра **max_features** сначала приводит к росту точности в интервале (15000, 17500), но затем дальнейший рост приводит к падению.

Увеличение параметра **maxlen** позволяет повысить значение точности.

Рост параметра **batch_size** приводит к росту точности в интервале (150, 175), но затем дальнейший рост приводит к ее падению.

In [8]:
# Построчное чтение файла Alice_in_Wonderland

with open("/content/Alice_in_Wonderland.txt", 'rb') as _in:
    lines = []
    for line in _in:
        line = line.strip().lower().decode("ascii", "ignore")
        if len(line) == 0:
            continue
        lines.append(line)
text = " ".join(lines)
chars = set([c for c in text])
nb_chars = len(chars)

In [9]:
char2index = {c: i for i, c in enumerate(chars)}
index2char = {i: c for i, c in enumerate(chars)}

In [10]:
SEQLEN, STEP = 20, 1
input_chars, label_chars = [], []

In [11]:
# Конвертация data в серии разных SEQLEN-length субпоследовательностей

for i in range(0, len(text) - SEQLEN, STEP):
    input_chars.append(text[i: i + SEQLEN])
    label_chars.append(text[i + SEQLEN])

In [12]:
# Вычисление one-hot encoding входных последовательностей X и следующего символа (the label) y

X = np.zeros((len(input_chars), SEQLEN, nb_chars), dtype=np.bool)
y = np.zeros((len(input_chars), nb_chars), dtype=np.bool)
for i, input_char in enumerate(input_chars):
    for j, ch in enumerate(input_char):
        X[i, j, char2index[ch]] = 1
    y[i, char2index[label_chars[i]]] = 1

In [13]:
# Установка ряда метапамертров  для нейронной сети и процесса тренировки

BATCH_SIZE, HIDDEN_SIZE = 1024, 512
NUM_ITERATIONS = 10 # 25 должно быть достаточно
NUM_EPOCHS_PER_ITERATION = 5
NUM_PREDS_PER_EPOCH = 100

In [14]:
model = Sequential()
model.add(
    GRU(  
        HIDDEN_SIZE,
        return_sequences=False,
        input_shape=(SEQLEN, nb_chars),
        unroll=True
    )
)
model.add(Dense(nb_chars))
model.add(Activation("softmax"))
model.compile(loss="categorical_crossentropy", optimizer="rmsprop")

In [15]:
# Выполнение серий тренировочных и демонстрационных итераций 

for iteration in range(NUM_ITERATIONS):

    # Для каждой итерации запуск передачи данных в модель 
    print("=" * 50)
    print("Итерация #: %d" % (iteration))
    model.fit(X, y, batch_size=BATCH_SIZE, epochs=NUM_EPOCHS_PER_ITERATION)

    test_idx = np.random.randint(len(input_chars))
    test_chars = input_chars[test_idx]

    print("Генерация из посева: %s" % (test_chars))
    print(test_chars, end="")
    for i in range(NUM_PREDS_PER_EPOCH):

        X_test = np.zeros((1, SEQLEN, nb_chars))
        for j, ch in enumerate(test_chars):
            X_test[0, j, char2index[ch]] = 1

        pred = model.predict(X_test, verbose=0)[0]
        y_pred = index2char[np.argmax(pred)]

        print(y_pred, end="")

        test_chars = test_chars[1:] + y_pred
print()

Итерация #: 0
Epoch 1/5
156/156 [==============================] - 28s 122ms/step - loss: 2.6799
Epoch 2/5
156/156 [==============================] - 19s 122ms/step - loss: 2.0912
Epoch 3/5
156/156 [==============================] - 19s 122ms/step - loss: 1.9054
Epoch 4/5
156/156 [==============================] - 19s 122ms/step - loss: 1.7726
Epoch 5/5
156/156 [==============================] - 19s 122ms/step - loss: 1.6655
Генерация из посева: nnyworth only of bea
nnyworth only of beatting of the works of the works of the works of the works of the works of the works of the works of ==================================================
Итерация #: 1
Epoch 1/5
156/156 [==============================] - 19s 122ms/step - loss: 1.5739
Epoch 2/5
156/156 [==============================] - 19s 122ms/step - loss: 1.4937
Epoch 3/5
156/156 [==============================] - 19s 121ms/step - loss: 1.4232
Epoch 4/5
156/156 [==============================] - 19s 121ms/step - loss: 1.3581
Epoch 5/5
15

1. Было увеличино количество итераций, чтобы модель успела обучиться должным образом.
2. При увеличении HIDDEN_SIZE модель обучается быстрее (loss снижается быстрее), так как модель становится лучше.
3. При увеличении SEQLEN модель обучается быстрее, но каждая эпоха длится дольше, так как модель обучается на более длинной последовательности слов.

Варианты решения проблемы исчезающего градиента в RNN:
1. Использование архитектур наподобие LSTM;
2. Инициализировать веса так, чтобы минимизировать вероятность затухания градиентов.